version: "3.9"
services:
  rabbit1:
    image: rabbitmq:management-alpine
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"
    volumes:
      - rabbit1:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit1
      RABBITMQ_DEFAULT_PASS: P4ssw0rd!
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - ssenet1
  rabbit2:
    image: rabbitmq:management-alpine
    ports:
      - "127.0.0.1:5674:5672"
      - "127.0.0.1:15674:15672"
    volumes:
      - rabbit2:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit2"
      RABBITMQ_DEFAULT_PASS: "P4ssw0rd!"
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - ssenet2
networks:
  ssenet1:
  ssenet2:
volumes:
  rabbit1:
  rabbit2: